[package]
edition = "2021"
name = "collections"
version = "0.1.0"

[dependencies]
indexmap = "1.7.0" 
maplit = "1.0.2"
paste = "1.0"

[dev-dependencies]
criterion = { version = "0.3", features = ["html_reports"] }