[package]
edition = "2021"
name = "more_collections"
authors = ["Rinde van Lon <rindevanlon@gmail.com>"]
description = "Additional collections not found in std::collections"
version = "0.1.0"
license = "Apache-2.0"
keywords = ["collections", "multimap"]
categories = ["data-structures"]
include = [ "LICENSE", "README.md", "**/*.rs", "Cargo.toml" ]

[dependencies]
indexmap = "1.7.0" 
maplit = "1.0.2"

[dev-dependencies]
criterion = { version = "0.3", features = ["html_reports"] }