[package]
edition = "2021"
name = "more_collections"
version = "0.10.0"
authors = ["Rinde van Lon <rindevanlon@gmail.com>"]
description = "Additional collections not found in std::collections"
repository = "https://github.com/rinde/more_collections/"
homepage = "https://github.com/rinde/more_collections/"
license = "Apache-2.0"
keywords = ["collections", "multimap"]
categories = ["data-structures"]
include = ["LICENSE", "README.md", "**/*.rs", "Cargo.toml"]

[features]
all = ["hashsetmultimap", "hashvecmultimap", "indexsetmultimap", "indexvecmultimap", "smallset", "smallmap"]
hashsetmultimap = ["maplit"]
hashvecmultimap = []
indexsetmultimap = ["indexmap"]
indexvecmultimap = ["indexmap"]
smallmap = ["indexmap", "smallvec"]
smallset = ["indexmap", "smallvec", "smallmap"]

[dependencies]
indexmap = { version = "2.1.0", optional = true }
maplit = { version = "1.0.2", optional = true }
smallvec = {version = "1.11.2", features = ["const_generics", "const_new", "union"], optional = true }

[dev-dependencies]
criterion = { version = "0.5.1", features = ["html_reports"] }
indexmap = { version = "2.1.0" }
maplit = { version = "1.0.2" }
more_collections = { path=".", features = ["all"]}
rand = "0.8.5"
itertools = "0.12.0"

[[bench]]
name = "vec_map"
harness = false

[profile.bench]
# opt-level = 1  
lto = true

[lints.rust]
# missing_debug_implementations = "warn"
nonstandard-style = "deny"

[lints.rustdoc]
broken_intra_doc_links = "deny"
private_intra_doc_links = "allow"

[lints.clippy]
correctness = "deny"
suspicious = "warn"
complexity = "warn"
perf = "deny"
cargo = "warn"
style = "warn"
todo = "deny"
doc_link_with_quotes = "warn"
doc_markdown = "warn"
cloned_instead_of_copied = "warn"
checked_conversions = "warn"
filter_map_next = "warn"
manual_instant_elapsed = "warn"
cast_possible_wrap = "warn"
cast_lossless = "warn"
