[package]
edition = "2021"
name = "more_collections"
version = "0.6.1"
authors = ["Rinde van Lon <rindevanlon@gmail.com>"]
description = "Additional collections not found in std::collections"
repository = "https://github.com/rinde/more_collections/"
homepage = "https://github.com/rinde/more_collections/"
license = "Apache-2.0"
keywords = ["collections", "multimap"]
categories = ["data-structures"]
include = ["LICENSE", "README.md", "**/*.rs", "Cargo.toml"]

[features]
all = ["hashsetmultimap", "hashvecmultimap", "indexsetmultimap", "indexvecmultimap", "smallset", "smallmap"]
hashsetmultimap = ["maplit"]
hashvecmultimap = []
indexsetmultimap = ["indexmap"]
indexvecmultimap = ["indexmap"]
smallmap = ["indexmap", "smallvec"]
smallset = ["indexmap", "smallvec", "smallmap"]

[dependencies]
indexmap = { version = "2.0.1", optional = true }
maplit = { version = "1.0.2", optional = true }
smallvec = {version = "1.11.1", features = ["const_generics", "const_new", "union"], optional = true }

[dev-dependencies]
criterion = { version = "0.5.1", features = ["html_reports"] }
indexmap = { version = "2.0.1" }
maplit = { version = "1.0.2" }
more_collections = { path=".", features = ["all"]}
