imports_granularity = "Item"
wrap_comments = true
format_code_in_doc_comments = true
normalize_comments = true
normalize_doc_attributes = true
group_imports = "StdExternalCrate"
report_todo = "Always"
report_fixme = "Always"
use_field_init_shorthand = true